apiVersion: v1
kind: Secret
metadata:
    name: db-root-creds
    namespace: kubecolors-prod
    labels:
        app: kubecolors
        resource: database
        component: root-credentials
type: Opaque
stringData:
    MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:hB+LMok=,iv:tkEEtE3beUQX6yIog7HmEXmddkE+RJ2sa3bM1bLd228=,tag:t2r+h3a+dPj/fF8RwKDMdQ==,type:str]
    MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:17cJzXQ=,iv:TeWJpeE/Kro1dDjfZpZRagRMbYQ5S3ocTEwOAiDXPFQ=,tag:UCRcy1rBSsmNwNij0NG1mg==,type:str]
sops:
    age:
        - recipient: age192pug0cpm4wedex36afp7zfnt0jjc4wlp85mwujc63t5a8vy2psq0en2hz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOGtUY1N4NjdqdTMzRUtk
            djVYOWNxMTNLLzd6WC9pamRqNDJWcXdiT0hVCnZiQk9XQm9wZEVWRmY4MlFTRmJz
            RndqZFBUNC9DOVcvMXRZTmRPdXp1elEKLS0tIDZpbmhOODV6aGxoNGZlZkxnR0JP
            c2E2bGJzYW5QSGpJdEZhbTFic1Y5UmMK2VoAM93BMT2uak5l5JVRn8dyq+eUBLl5
            hXjPW6XEz2kdlCdh6q6/wQg9t4hRV+MTnomx9xIbwfhW09LPJx0DHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T16:55:10Z"
    mac: ENC[AES256_GCM,data:SBXBjr2b3DN9GGUHdllWH5KCLcaYcl4K0b5fG5ckhJ9woOhLmxV65roI8+kS43goRTL/6gYrC/syTjotyNYlLOsG5zfgHZmak4DrrxwpbYXlJnPrFFM3y5tOHHr8GJ6uQw3vlCun2g/xdCnPsGRdpXLbOKI030QgMIoQ536fSmI=,iv:InFc3iGf2YGfWXhbY91uefeKsUnzIhBYeMvKz/useoc=,tag:ViXAkEwflTN39A2+kOo6wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
