apiVersion: v1
kind: Secret
metadata:
    name: db-creds
    labels:
        app: kubecolors
        resource: database
        component: user-credentials
type: Opaque
stringData:
    COLORS_DATABASE: ENC[AES256_GCM,data:OKKJx7Sa,iv:F9RE1AgpRAjjH/cSxy1IfWdUDq147GyptiimJs798jE=,tag:jfa40BZRUp6sAuMeA8XWGA==,type:str]
    COLORS_USERNAME: ENC[AES256_GCM,data:XEtwKFlY,iv:qOYBGokHtSk3A7FPFYFW20x1/3X4a3AM91uGhPCKVn8=,tag:lHuX4uwqz4oVqoIpAq9QZA==,type:str]
    COLORS_PASSWORD: ENC[AES256_GCM,data:x4VwiIVd,iv:8uv0BBBeaWPCjUvqub1j5CQa+eIrEmsSJKDQbA3zg1I=,tag:UlnG1kD7ihVohL//PXvDgQ==,type:str]
sops:
    age:
        - recipient: age192pug0cpm4wedex36afp7zfnt0jjc4wlp85mwujc63t5a8vy2psq0en2hz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkV3VaVFE2TmRoYTlRQ0xK
            aFd4NHFLaUl5QlRIZDZMUHJ3YTRQWGVTeG5BClJBZjBiU2RtK1g2SUpoaGNoWEhS
            Vm5DTmYrU2ljRGh2RW9WeWduSEY1ejQKLS0tIDRLU0dPaUhLT3JGdUZHMGFqbCtO
            RElTa3RCLysxZFlxVGFrQmVTN0FCeTgKsafxKoCgRAFCymP047W71/ZLTJD/UmD2
            BYK26N4DkH1kfzBRQqeIcgTCO97EaFIv5DuPCpPJ6fM9keCGVmSISA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T17:20:54Z"
    mac: ENC[AES256_GCM,data:7QTJ6ykreBaESKaed0DCEvYB6WDRSgqQ5bsYzw8iTJgLrzfGkst09z77iBFUFAj4/RIVyThn+xay+uz/Oo6fdC4qTqC4XhoHrxjOarRf/giJ93IEFD+P15J+Kp0Vb+hfQUlcBoKoqTA8bbAMaShO+sq12ghXm5AUOy/6YfLmDXs=,iv:kyoSgCuTvC6zD30YC8kVbZxCoxNExOKIzI6G9ew+2NE=,tag:HmPVgAnbVUUyLjXVpS7EXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
