apiVersion: v1
kind: Secret
metadata:
    name: db-root-creds
    labels:
        app: kubecolors
        resource: database
        component: root-credentials
type: Opaque
stringData:
    MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:u1hMEE4=,iv:rGwn2DQz+1ZTDiILIGYpWUIyTu7thYC69oK9juU+NTw=,tag:kitBhG969K0ADF5OzN4fgg==,type:str]
    MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:T9+Y7sE=,iv:ww6I0mrYyvIBfvEozjG9QIIrNk2emzDG4ABTHnPlW/E=,tag:+E5rS1vqU0W3haNLQ6IJIQ==,type:str]
sops:
    age:
        - recipient: age192pug0cpm4wedex36afp7zfnt0jjc4wlp85mwujc63t5a8vy2psq0en2hz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaW84U1JFcGh0aGlRMFM0
            cUYzdWNwQTU1Rk5qT1NhZEdqdDJwY0NCRnljCnpDK3dZNG5aclJVaXU5bFYyZnFx
            MnZzWFBqL01aZW81NFltUkZqdnZuMUEKLS0tIGl6WlJHaklSeHBONElyUmwvZUsv
            ckpzR28xbDNYS3JIaVdWc1JwNDN0LzgKBbDW2DSeGj2osDd/128m63R/6FPC/blN
            s8JkaXOXjkRE8KuR9uKe7iWV8YVx9BalEcPez//eON2XrYlxymfFQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T17:20:57Z"
    mac: ENC[AES256_GCM,data:BucfInrKRBeSn8cyyWgmTclNBzmerQ1/aC4gsz5B/D3yGVrWoP5Ms/0BEtW3tXUSoVqA5+m99Sa+OAFPzbEhuG9yrwF4XvP1bk//7TDsIPFKFXIV6bl5HHtGG9Y4dkJpx50hXQOMJg264qneWL96SdoYFkygJO+W2mj1DuIYizI=,iv:942V8eh5mQMwwNCwebzSYqHIZ8LaEMSbQ3c8oa4EC0s=,tag:GR3vbLSqCrKXhAR8aiuucA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
