apiVersion: v1
kind: Secret
metadata:
  name: db-creds
  labels:
    app: kubecolors
    resource: database
    component: user-credentials
type: Opaque
stringData:
  COLORS_DATABASE: colors
  COLORS_USERNAME: colors
  COLORS_PASSWORD: colors
