apiVersion: v1
kind: Secret
metadata:
  name: db-root-creds
  labels:
    app: kubecolors
    resource: database
    component: root-credentials 
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: mongo
  MONGO_INITDB_ROOT_PASSWORD: mongo
