apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - database/db-init.yaml
  - database/db.yaml
  - backend/color-api.config.yaml
  - backend/color-api.deployment.yaml
  - backend/color-api.service.yaml
  - network-policies/deny-ingress.yaml
  - network-policies/allow-colorapi-ingress.yaml
  - network-policies/allow-external-traffic.yaml
