apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubecolors

resources:
  - kubecolors-namespace.yaml
  - ../../base

images:
  - name: penikolov23/color-api
    newTag: "2.1.0"

patches:
  # Storage class for local Docker Desktop
  - target:
      kind: StatefulSet
      name: mongo-shards
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: hostpath

  # NodePort service for local access
  - target:
      kind: Service
      name: color-api
    patch: |-
      - op: add
        path: /spec/type
        value: NodePort

  - path: patches/probe-initial-delay-10s.yaml
