apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-api
  labels:
    app: kubecolors
    resource: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubecolors
      resource: backend
      component: color-api
  template:
    metadata:
      labels:
        app: kubecolors
        resource: backend
        component: color-api
    spec:
      containers:
        - name: color-api
          image: penikolov23/color-api:2.0.0
          env:
            - name: PORT
              value: "80"
          envFrom:
            - secretRef:
                name: db-creds
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          startupProbe:
            httpGet:
              path: /up
              port: 80
            failureThreshold: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            failureThreshold: 2
            periodSeconds: 10
          volumeMounts:
            - name: application-config
              mountPath: /app/config/
      volumes:
        - name: application-config
          configMap:
            name: color-api-config
