apiVersion: v1
kind: Secret
metadata:
    name: db-root-creds
    namespace: kubecolors
    labels:
        app: kubecolors
        resource: database
        component: root-credentials
type: Opaque
stringData:
    MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:hB+LMok=,iv:tkEEtE3beUQX6yIog7HmEXmddkE+RJ2sa3bM1bLd228=,tag:t2r+h3a+dPj/fF8RwKDMdQ==,type:str]
    MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:17cJzXQ=,iv:TeWJpeE/Kro1dDjfZpZRagRMbYQ5S3ocTEwOAiDXPFQ=,tag:UCRcy1rBSsmNwNij0NG1mg==,type:str]
sops:
    age:
        - recipient: age192pug0cpm4wedex36afp7zfnt0jjc4wlp85mwujc63t5a8vy2psq0en2hz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOGtUY1N4NjdqdTMzRUtk
            djVYOWNxMTNLLzd6WC9pamRqNDJWcXdiT0hVCnZiQk9XQm9wZEVWRmY4MlFTRmJz
            RndqZFBUNC9DOVcvMXRZTmRPdXp1elEKLS0tIDZpbmhOODV6aGxoNGZlZkxnR0JP
            c2E2bGJzYW5QSGpJdEZhbTFic1Y5UmMK2VoAM93BMT2uak5l5JVRn8dyq+eUBLl5
            hXjPW6XEz2kdlCdh6q6/wQg9t4hRV+MTnomx9xIbwfhW09LPJx0DHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T18:16:46Z"
    mac: ENC[AES256_GCM,data:XIWFm/RNxfBjbYwU08knT+7YqM+S+mlfBHMimMMjPp03FMCw6/V7hbVJc25+SEnFCFqsNGdsAOO29TSNHyMOycGDj5T1Nr3AnxeLgCnMg7lgdxxIXcwnLMP4Ld+X446yfIzahCmcjUbMPJEXcPHq5FVNI+ou1/NVPeReRZVJ9kA=,iv:+bfZwvRHWio5NAH+nR3qQwYYcoNq+8po/m1rDHuR5OE=,tag:TGd4QM8GLnqs5H90rbQuJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
