apiVersion: v1
kind: Secret
metadata:
    name: db-creds
    namespace: kubecolors-dev
    labels:
        app: kubecolors
        resource: database
        component: user-credentials
type: Opaque
stringData:
    COLORS_DATABASE: ENC[AES256_GCM,data:FCTchVcB,iv:Es4fgRL8B8WO2eHI0Depz0DFqboOIBy862SEy2VVKBQ=,tag:hd5uc/VDnTqI7Bjs/2r7yQ==,type:str]
    COLORS_USERNAME: ENC[AES256_GCM,data:dir7p6OL,iv:oXiXWpqVlKs1PTzkHjGLwIiNCCugIlQwn9iif8jLEQM=,tag:bnoIHvtsDd9Ldff7875pxg==,type:str]
    COLORS_PASSWORD: ENC[AES256_GCM,data:0GBOYZJA,iv:D3bEqbZlgnGFY8UBe3PVfedZxOXrVN60FOrIvKmGQ2M=,tag:BMfuWTxwV2qFs4hwM3AP9Q==,type:str]
sops:
    age:
        - recipient: age192pug0cpm4wedex36afp7zfnt0jjc4wlp85mwujc63t5a8vy2psq0en2hz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMlZOaHJZeWZTYXRUakVp
            S3FRdE9PRWlzd2RFSFozcHBVMVIzaGFaVWg0Cm9tdjV6cnBCUmo3d21QUTd5R21S
            amRqdkljSGJTTFcrSzNVZGFkOWVrY1kKLS0tIHlVdnBVMlB3Mm41MXIvcjVBcE5F
            OHJnUzBDVHpCRTliRXQzOG4zZVpOYzgKRcrFTGowfSdYd4XZITtflTjiYl4JYMr9
            bv/zln6RA4CAIMZAHBqwtmYAMRpCwuSu0hpd9HcVWC0kqsP6qwk0Uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T16:55:10Z"
    mac: ENC[AES256_GCM,data:DmMhKEG88PSmlgLzFPGlc1r6L3dwUjseQ+g1EiT5IaTxBP6rZ80iLcdSoSSZTM8Cs99oBrFn5kejTFsbO0A0WyLX6ZJ0gFBRB5zQmhmZtDhugpzsXdBwxOEhBIIy/MFssqAaNHeLvai1ANB9e0OUZgHSeBwxKUTbDAesq0/HBK0=,iv:cUXy3qcn4amkhl39/pJZbA1KkjR0uMgEGGKCIMH4YSc=,tag:Ys9iEAl5VQSaLJfb0UpBWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
